### ISSUE TITLE
Improve integration between Chargify/Stripe/Xero/Capsule for finance team

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#451]
As a member of the finance team (@alisonwalters) I want the integration between Chargify / Stripe / Xero / Capsule systems to work as smoothly as possible

* so that a new member sign ups initiates an invoice in Xero correctly.
* so that VAT is recognised on invoices produced automatically in Xero on member sign -ups
* Ensuring each member receives an appropriate VAT invoice via the Chargify system on sign up
* d so that we can have bespoke finance reports from chargify and Xero to account for different membership types and discount codes. (Current Chargify finance report setup described: https://docs.google.com/a/theodi.org/spreadsheets/d/14SgdTL97Y0kweNEFhykxjGXPkCaJ-gxcPzL3AAE-mmc/edit?usp=drive_web).This would need to be reported in financial terms for each membership type as well as recording actual numbers of each membership and coupon type on a monthly basis.

Sub-issues:
* [ ] 100% discounted invoices: #374
* [ ] Invoice payments coming up paid in Xero: #450
* [ ] Finance report coupon and discount data: #380
* [ ] Chargify::Coupon.all doesn't return all coupons: #387
* [ ] Booking value overcount: #396
* [ ] Booking value report monthly subscriptions: #397
* [ ] Booking value report needs to break down by pricing: #398
* [ ] Regularly fetch coupon/pricing info from chargify: #422

**Comment by Floppy** [comment]
Further detail on reports. @greenreveller can these comments be moved to the ticket they are relevant to, or created as new tickets?

* The problems arises in the Chargify finance report because it counts the number of each type of membership in the month. At the moment it is counting all payments but sometimes these payments are monthly payments. We only need it to count payments that are new memberships. I can see this might be difficult as new memberships can be monthly or annual payments so it might be difficult to pick up in that sometimes a new membership pays only 1/12 of the membership value whilst others pay the full price. I’m wondering if there is another area on chargify / Capsule that this could be picked up from ?
* Also in the ‘counting’ report, the count does not pick up if a sale is immediately refunded. we would not want to count this as a sale
* The count report is not picking up numbers of zero value memberships or discounted memberships which we do want to count
* Where payments are being made monthly, the ‘count’ report is picking up each monthly payments as a new member

**Comment by greenreveller** [comment]
2 Cash reporting dcouments required - one for monthly sign-ups and one for annual sign-ups
